stages:
  - build
  - singularity

build-docker:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_BUILDKIT: 1
    GIT_STRATEGY: clone
    GIT_DEPTH: 0
    TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build 
      --label ci.timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      --label ci.builder=$GITLAB_USER_LOGIN
      --label ci.image=$CI_REGISTRY_IMAGE
      --label ci.tag=$CI_COMMIT_REF_NAME
      --label ci.commit=$CI_COMMIT_SHA 
      -t $TAG .
    - DIGEST=$(docker inspect --format='{{index .Id}}' $TAG)
    - echo "FROM $TAG" | docker buildx build --label ci.digest=$DIGEST -t $TAG --push -
  only:
    - tags

build-singularity:
  image: quay.io/singularity/singularity:v3.11.4
  stage: singularity
  variables:
    GIT_STRATEGY: none
  script:
    - VERSION=${CI_COMMIT_REF_NAME#v}
    - singularity build catnus_${CI_COMMIT_REF_NAME}.sif docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - ls -lh catnus_${CI_COMMIT_REF_NAME}.sif
  artifacts:
    paths:
      - catnus_${CI_COMMIT_REF_NAME}.sif
    expire_in: never
  only:
    - tags
  needs:
    - build-docker

